In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
dataset = pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset, drop_first=True).astype(int)

In [5]:
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [8]:
dependent = dataset[['charges']]

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
dependent = np.ravel(dependent)
param_grid = {
    'criterion':['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],
    'max_features': ['sqrt','log2',None],
    'n_estimators':[10,100]
}

grid = GridSearchCV(RandomForestRegressor(), param_grid, refit=True, verbose=3, n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['sqrt', 'log2', None],
                         'n_estimators': [10, 100]},
             verbose=3)

In [10]:
result = grid.cv_results_

print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'absolute_error', 'max_features': 'sqrt', 'n_estimators': 100}:

In [11]:
table=pd.DataFrame.from_dict(result)

In [12]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.251061,0.052199,0.018408,0.014979,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.832061,0.750447,0.831321,0.815393,0.809728,0.807790,0.029975,23
1,1.156491,0.046416,0.041615,0.002940,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.855562,0.771377,0.848324,0.826278,0.834860,0.827280,0.029754,7
2,0.118025,0.003408,0.009607,0.002060,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.841050,0.771200,0.822524,0.801041,0.830834,0.813330,0.024841,19
3,1.171093,0.036851,0.042815,0.004793,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.853467,0.766420,0.853295,0.826069,0.837558,0.827362,0.032167,6
4,0.200247,0.052989,0.008405,0.001856,squared_error,None,10,"{'criterion': 'squared_error', 'max_features':...",0.836816,0.748349,0.837182,0.781311,0.819754,0.804682,0.034744,24
5,1.666417,0.069514,0.046815,0.006113,squared_error,None,100,"{'criterion': 'squared_error', 'max_features':...",0.841585,0.766218,0.859696,0.810377,0.827239,0.821023,0.031856,10
6,0.128228,0.004623,0.009407,0.001960,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.829444,0.752985,0.842703,0.815498,0.827072,0.813540,0.031487,18
7,1.085872,0.086814,0.039012,0.002966,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.854929,0.775851,0.854323,0.822446,0.829460,0.827402,0.028875,5
8,0.122428,0.002418,0.008805,0.001600,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.845841,0.751839,0.839936,0.816651,0.821192,0.815092,0.033476,17
9,1.168487,0.031665,0.045616,0.004843,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.853394,0.773380,0.849432,0.825977,0.837077,0.827852,0.028892,4
10,0.163839,0.001168,0.010004,0.002830,friedman_mse,None,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.833924,0.749449,0.840413,0.800545,0.827541,0.810374,0.033347,20
11,1.663417,0.052352,0.041214,0.003125,friedman_mse,None,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.842173,0.769112,0.852565,0.807667,0.827435,0.819790,0.029492,12
12,0.331080,0.044178,0.008805,0.001940,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.849889,0.749594,0.831165,0.814509,0.832131,0.815458,0.034783,15
13,2.926338,0.139168,0.040012,0.006418,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.859172,0.772819,0.852037,0.825724,0.839805,0.829911,0.030727,1
14,0.304272,0.014543,0.008606,0.001744,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.841560,0.769480,0.825859,0.822541,0.827967,0.817481,0.024858,13
15,2.989555,0.039664,0.041412,0.010309,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.855568,0.772603,0.854438,0.826093,0.838925,0.829525,0.030460,2
16,0.507123,0.012183,0.007206,0.000749,absolute_error,None,10,"{'criterion': 'absolute_error', 'max_features'...",0.831830,0.756034,0.846333,0.815856,0.825751,0.815161,0.031171,16
17,4.996264,0.119087,0.036012,0.003523,absolute_error,None,100,"{'criterion': 'absolute_error', 'max_features'...",0.835365,0.756410,0.861073,0.815868,0.840178,0.821779,0.035708,9
18,0.134829,0.005707,0.008006,0.001096,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.839076,0.766791,0.841160,0.813914,0.816433,0.815475,0.026796,14
19,1.287121,0.023410,0.039414,0.003137,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.852771,0.774400,0.853576,0.824367,0.834988,0.828020,0.028992,3
20,0.139031,0.005404,0.008606,0.001199,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.831067,0.761394,0.825785,0.798219,0.823276,0.807948,0.025882,22
21,1.277517,0.011069,0.040414,0.003138,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.851889,0.773983,0.851091,0.822316,0.836979,0.827252,0.028747,8
22,0.190045,0.011174,0.007806,0.000401,poisson,None,10,"{'criterion': 'poisson', 'max_features': None,...",0.832840,0.747329,0.853328,0.795995,0.821929,0.810284,0.036509,21
23,1.634810,0.115639,0.038813,0.003765,poisson,None,100,"{'criterion': 'poisson', 'max_features': None,...",0.840103,0.770263,0.856623,0.804434,0.829220,0.820129,0.030154,11

In [13]:
Age_input=int(input("Age:"))
BMI_input=float(input("BMI:"))
Child_input=int(input("Children:"))
Gender_input=int(input("Sex Male 0 or 1:"))
Smoker_input=int(input("Smoker Yes 0 or 1:"))

Age:56
BMI:44
Children:1
Sex Male 0 or 1:0
Smoker Yes 0 or 1:0

In [14]:
Future_Prediction=grid.predict([[Age_input,BMI_input,Child_input,Gender_input,Smoker_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[12221.675]

C:\Users\ELCOT\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(