In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset, drop_first=True).astype(int)

In [5]:
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [8]:
dependent = dataset[['charges']]

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [19]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor

param_grid = {
    'criterion':['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],
    'max_features': ['sqrt','log2'],
    'splitter':['best','random']
}

grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit=True, verbose=3, n_jobs=-1)
grid.fit(X_train, Y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [20]:
result = grid.cv_results_
grid_predictions = grid.predict(X_test)

from sklearn.metrics import r2_score
r_score=r2_score(Y_test,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'criterion': 'poisson', 'max_features': 'sqrt', 'splitter': 'best'}: 0.7329938231360947

In [21]:
table=pd.DataFrame.from_dict(result)

In [22]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.015998,0.000008,0.008002,0.000005,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.672068,0.540224,0.641237,0.501163,0.624814,0.595901,0.064448,7
1,0.017600,0.003202,0.004798,0.003917,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.670875,0.600932,0.671696,0.494627,0.578510,0.603328,0.065840,5
2,0.025600,0.003198,0.006400,0.005987,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.584975,0.516242,0.652203,0.601319,0.636907,0.598329,0.047573,6
3,0.016001,0.005058,0.009600,0.003201,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.587036,0.353958,0.687095,0.659264,0.529428,0.563356,0.118380,13
4,0.025604,0.007842,0.006402,0.005987,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.692174,0.651823,0.593367,0.567933,0.527175,0.606494,0.058901,4
5,0.019204,0.006402,0.006401,0.005988,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.527751,0.534955,0.718613,0.520489,0.604903,0.581342,0.075000,10
6,0.019204,0.003919,0.009600,0.009329,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.659935,0.512931,0.533589,0.559930,0.535461,0.560369,0.051964,14
7,0.019202,0.003918,0.008000,0.000004,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.659677,0.467744,0.637202,0.607722,0.538375,0.582144,0.070285,9
8,0.052806,0.010852,0.004801,0.003920,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.637781,0.631464,0.705506,0.304838,0.624683,0.580854,0.141029,12
9,0.035200,0.008157,0.008004,0.005060,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.635955,0.494766,0.463409,0.616251,0.412779,0.524632,0.087107,16
10,0.046404,0.005987,0.004803,0.003922,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.714949,0.655965,0.618293,0.641684,0.606251,0.647428,0.037972,3
11,0.032002,0.000002,0.012804,0.003916,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.588657,0.516391,0.561797,0.605061,0.633734,0.581128,0.039903,11
12,0.020802,0.003922,0.008003,0.000005,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.663105,0.643115,0.673722,0.638825,0.692134,0.662180,0.019699,1
13,0.017603,0.003202,0.004800,0.003919,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.715176,0.618498,0.737194,0.612409,0.605693,0.657794,0.056419,2
14,0.022402,0.005989,0.008003,0.005060,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.639586,0.528148,0.573390,0.665972,0.509640,0.583347,0.060940,8
15,0.016003,0.005062,0.009603,0.003198,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.601288,0.504030,0.558510,0.547548,0.579357,0.558146,0.032717,15

In [23]:
Age_input=int(input("Age:"))
BMI_input=float(input("BMI:"))
Child_input=int(input("Children:"))
Gender_input=int(input("Sex Male 0 or 1:"))
Smoker_input=int(input("Smoker Yes 0 or 1:"))

Age:56
BMI:45
Children:2
Sex Male 0 or 1:1
Smoker Yes 0 or 1:1

In [24]:
F_Prediction=grid.predict([[Age_input,BMI_input,Child_input,Gender_input,Smoker_input]])
print("Future_Prediction={}".format(F_Prediction))

Future_Prediction=[48549.]