In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
dataset = pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset, drop_first=True).astype(int)

In [5]:
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [8]:
dependent = dataset[['charges']]

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [26]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [27]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

param_grid = {
    'criterion':['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],
    'max_features': ['sqrt','log2',None],
    'n_estimators':[10,100]
}

grid = GridSearchCV(RandomForestRegressor(), param_grid, refit=True, verbose=3, n_jobs=-1)
grid.fit(X_train,Y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['sqrt', 'log2', None],
                         'n_estimators': [10, 100]},
             verbose=3)

In [35]:
result = grid.cv_results_
grid_predictions = grid.predict(X_test)

from sklearn.metrics import r2_score
r_score=r2_score(Y_test,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'criterion': 'absolute_error', 'max_features': 'log2', 'n_estimators': 100}: 0.8698244378538675

In [36]:
table=pd.DataFrame.from_dict(result)

In [37]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.236826,0.015679,0.016002,0.005060,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.772424,0.755462,0.813744,0.796935,0.755637,0.778840,0.023116,21
1,1.078521,0.094858,0.035206,0.003918,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.804528,0.767922,0.834259,0.826924,0.755000,0.797727,0.031456,3
2,0.102407,0.003211,0.008001,0.005062,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.783941,0.727896,0.831840,0.823052,0.731225,0.779591,0.043930,18
3,0.976111,0.011314,0.033603,0.003200,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.805884,0.768857,0.835271,0.817089,0.753333,0.796087,0.030469,7
4,0.139217,0.008159,0.008001,0.005060,squared_error,None,10,"{'criterion': 'squared_error', 'max_features':...",0.807473,0.722793,0.817894,0.800361,0.757337,0.781171,0.035734,16
5,1.329749,0.032558,0.040008,0.005061,squared_error,None,100,"{'criterion': 'squared_error', 'max_features':...",0.815907,0.752803,0.821681,0.811460,0.759892,0.792348,0.029658,11
6,0.104013,0.005060,0.008002,0.005060,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.804497,0.730546,0.794757,0.796711,0.739707,0.773244,0.031426,23
7,0.976109,0.018245,0.036805,0.003917,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.804005,0.759017,0.834605,0.821782,0.751623,0.794206,0.033287,9
8,0.108813,0.009600,0.008002,0.005062,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.792645,0.739845,0.811126,0.806556,0.750549,0.780144,0.029372,17
9,0.998513,0.018522,0.041606,0.003202,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.816237,0.758865,0.831456,0.821277,0.751930,0.795953,0.033546,8
10,0.136018,0.000004,0.006398,0.003199,friedman_mse,None,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.812797,0.742821,0.823484,0.780639,0.756717,0.783292,0.031103,13
11,1.177733,0.124711,0.032004,0.007156,friedman_mse,None,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.806947,0.757036,0.828509,0.809945,0.758811,0.792250,0.028990,12
12,0.155218,0.008158,0.003201,0.003920,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.780797,0.777197,0.817395,0.782765,0.724367,0.776504,0.029828,22
13,1.648185,0.184194,0.032005,0.005060,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.809227,0.762821,0.834597,0.824469,0.751418,0.796506,0.033354,5
14,0.190421,0.005990,0.006399,0.003200,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.801093,0.752609,0.825800,0.780809,0.733963,0.778855,0.032883,20
15,1.920213,0.039523,0.030406,0.003200,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.808116,0.770423,0.836056,0.834318,0.756866,0.801156,0.032473,1
16,0.318434,0.009332,0.004803,0.003921,absolute_error,None,10,"{'criterion': 'absolute_error', 'max_features'...",0.780399,0.780073,0.776680,0.801609,0.758033,0.779359,0.013846,19
17,2.985935,0.202119,0.027205,0.006402,absolute_error,None,100,"{'criterion': 'absolute_error', 'max_features'...",0.795792,0.788165,0.813641,0.818265,0.751999,0.793572,0.023558,10
18,0.102413,0.009330,0.001600,0.003200,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.769777,0.720135,0.783148,0.801713,0.741601,0.763275,0.029139,24
19,0.979309,0.026097,0.032005,0.000002,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.810896,0.765016,0.836349,0.822344,0.753265,0.797574,0.032612,4
20,0.107213,0.003920,0.003200,0.003919,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.796910,0.755272,0.834480,0.793048,0.732120,0.782366,0.035497,14
21,0.988912,0.029765,0.035205,0.003919,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.812936,0.768679,0.826147,0.828540,0.755241,0.798308,0.030449,2
22,0.137612,0.003200,0.008002,0.000001,poisson,None,10,"{'criterion': 'poisson', 'max_features': None,...",0.810440,0.755903,0.803389,0.779724,0.759405,0.781772,0.022194,15
23,1.289744,0.066051,0.028805,0.008160,poisson,None,100,"{'criterion': 'poisson', 'max_features': None,...",0.815427,0.765816,0.825695,0.814053,0.761016,0.796401,0.027274,6

In [38]:
Age_input=int(input("Age:"))
BMI_input=float(input("BMI:"))
Child_input=int(input("Children:"))
Gender_input=int(input("Sex Male 0 or 1:"))
Smoker_input=int(input("Smoker Yes 0 or 1:"))

Age:33
BMI:43
Children:2
Sex Male 0 or 1:1
Smoker Yes 0 or 1:0

In [39]:
Future_Prediction=grid.predict([[Age_input,BMI_input,Child_input,Gender_input,Smoker_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[14263.37]